FROM golang:1.22-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o /mock-psp ./cmd/mock-psp

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /mock-psp /mock-psp
EXPOSE 9090
CMD ["/mock-psp"]
