version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: invoicedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d invoicedb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mock-psp:
    build:
      context: .
      dockerfile: Dockerfile.mockpsp
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      PORT: "9090"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mock-psp:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/invoicedb?sslmode=disable
      PSP_BASE_URL: http://mock-psp:9090
      PORT: "8080"
      SEED_DATA: "true"
